// packages/svelte/src/dialog/dialog.svelte
<script lang="ts">
  import { createEventDispatcher, onMount, onDestroy } from 'svelte'
  import { YIcon } from '../icon'

  interface Props {
    open?: boolean
    title?: string
    closable?: boolean
    mask?: boolean
    maskClosable?: boolean
    width?: string | number
  }

  export let open: Props['open'] = false
  export let title: Props['title'] = undefined
  export let closable: Props['closable'] = true
  export let mask: Props['mask'] = true
  export let maskClosable: Props['maskClosable'] = true
  export let width: Props['width'] = undefined

  const dispatch = createEventDispatcher<{ close: void }>()

  let previousFocus: HTMLElement | null = null

  function handleClose() {
    dispatch('close')
  }

  function handleOverlayClick() {
    if (maskClosable && mask) handleClose()
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && closable) handleClose()
  }

  $: if (open) {
    previousFocus = document.activeElement as HTMLElement
    document.addEventListener('keydown', handleKeydown)
    document.body.style.overflow = 'hidden'
  } else {
    document.removeEventListener('keydown', handleKeydown)
    document.body.style.overflow = ''
    if (previousFocus) previousFocus.focus()
  }

  onDestroy(() => {
    document.removeEventListener('keydown', handleKeydown)
    document.body.style.overflow = ''
  })

  $: dialogStyle = width != null
    ? `width: ${typeof width === 'number' ? `${width}px` : width}`
    : ''
</script>

{#if open}
  <div class="y-dialog-overlay" on:click={handleOverlayClick} role="presentation">
    {#if mask}
      <div class="y-dialog-mask" />
    {/if}
    <div
      class="y-dialog"
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? 'y-dialog-title' : undefined}
      style={dialogStyle}
      on:click|stopPropagation
      on:keydown|stopPropagation
    >
      {#if title || closable}
        <div class="y-dialog__header">
          {#if title}
            <h2 id="y-dialog-title" class="y-dialog__title">{title}</h2>
          {/if}
          {#if closable}
            <button
              type="button"
              class="y-dialog__close"
              aria-label="Close"
              on:click={handleClose}
            >
              <YIcon name="x" size={16} />
            </button>
          {/if}
        </div>
      {/if}
      <div class="y-dialog__body">
        <slot />
      </div>
      {#if $$slots.footer}
        <div class="y-dialog__footer">
          <slot name="footer" />
        </div>
      {/if}
    </div>
  </div>
{/if}

// packages/vue/src/dialog/dialog.vue
<script setup lang="ts">
import { watch, onBeforeUnmount, ref, computed } from 'vue'
import { YIcon } from '../icon'

export interface DialogProps {
  open?: boolean
  title?: string
  closable?: boolean
  mask?: boolean
  maskClosable?: boolean
  width?: string | number
  footer?: boolean
}

const props = withDefaults(defineProps<DialogProps>(), {
  open: false,
  closable: true,
  mask: true,
  maskClosable: true,
  footer: false,
})

const emit = defineEmits<{
  'update:open': [value: boolean]
  'close': []
}>()

const previousFocus = ref<HTMLElement | null>(null)

function handleClose() {
  emit('update:open', false)
  emit('close')
}

function handleOverlayClick() {
  if (props.maskClosable && props.mask) handleClose()
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape' && props.closable) handleClose()
}

watch(() => props.open, (isOpen) => {
  if (isOpen) {
    previousFocus.value = document.activeElement as HTMLElement
    document.addEventListener('keydown', handleKeydown)
    document.body.style.overflow = 'hidden'
  } else {
    document.removeEventListener('keydown', handleKeydown)
    document.body.style.overflow = ''
    if (previousFocus.value) previousFocus.value.focus()
  }
})

onBeforeUnmount(() => {
  document.removeEventListener('keydown', handleKeydown)
  document.body.style.overflow = ''
})

const dialogStyle = computed(() => {
  if (props.width == null) return {}
  return { width: typeof props.width === 'number' ? `${props.width}px` : props.width }
})
</script>

<template>
  <div v-if="open" class="y-dialog-overlay" @click="handleOverlayClick">
    <div v-if="mask !== false" class="y-dialog-mask" />
    <div
      class="y-dialog"
      role="dialog"
      aria-modal="true"
      :aria-labelledby="title ? 'y-dialog-title' : undefined"
      :style="dialogStyle"
      @click.stop
    >
      <div v-if="title || closable" class="y-dialog__header">
        <h2 v-if="title" id="y-dialog-title" class="y-dialog__title">{{ title }}</h2>
        <button
          v-if="closable"
          type="button"
          class="y-dialog__close"
          aria-label="Close"
          @click="handleClose"
        >
          <YIcon name="x" :size="16" />
        </button>
      </div>
      <div class="y-dialog__body">
        <slot />
      </div>
      <div v-if="footer || $slots.footer" class="y-dialog__footer">
        <slot name="footer" />
      </div>
    </div>
  </div>
</template>
