// packages/vue/src/card/card.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface CardProps {
  title?: string
  bordered?: boolean
  hoverable?: boolean
  size?: 'sm' | 'md' | 'lg'
  loading?: boolean
}

const props = withDefaults(defineProps<CardProps>(), {
  bordered: true,
  hoverable: false,
  size: 'md',
  loading: false,
})

const classes = computed(() =>
  [
    'y-card',
    `y-card--${props.size}`,
    props.bordered ? 'y-card--bordered' : '',
    props.hoverable ? 'y-card--hoverable' : '',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div :class="classes">
    <div v-if="$slots.cover" class="y-card__cover">
      <slot name="cover" />
    </div>
    <div v-if="title || $slots.extra" class="y-card__header">
      <h3 v-if="title" class="y-card__title">{{ title }}</h3>
      <div v-if="$slots.extra" class="y-card__extra">
        <slot name="extra" />
      </div>
    </div>
    <div class="y-card__body">
      <div v-if="loading" class="y-card__loading">
        <span class="y-card__loading-dot" />
        <span class="y-card__loading-dot" />
        <span class="y-card__loading-dot" />
      </div>
      <slot v-else />
    </div>
  </div>
</template>

// packages/react/src/card/card.tsx
import React, { forwardRef } from 'react'

export interface CardProps {
  title?: string
  extra?: React.ReactNode
  bordered?: boolean
  hoverable?: boolean
  size?: 'sm' | 'md' | 'lg'
  cover?: React.ReactNode
  loading?: boolean
  children?: React.ReactNode
  className?: string
}

const YCard = forwardRef<HTMLDivElement, CardProps>(
  (
    {
      title,
      extra,
      bordered = true,
      hoverable = false,
      size = 'md',
      cover,
      loading = false,
      children,
      className,
    },
    ref,
  ) => {
    const classes = [
      'y-card',
      `y-card--${size}`,
      bordered ? 'y-card--bordered' : '',
      hoverable ? 'y-card--hoverable' : '',
      className || '',
    ]
      .filter(Boolean)
      .join(' ')

    return (
      <div ref={ref} className={classes}>
        {cover && <div className="y-card__cover">{cover}</div>}
        {(title || extra) && (
          <div className="y-card__header">
            {title && <h3 className="y-card__title">{title}</h3>}
            {extra && <div className="y-card__extra">{extra}</div>}
          </div>
        )}
        <div className="y-card__body">
          {loading ? (
            <div className="y-card__loading">
              <span className="y-card__loading-dot" />
              <span className="y-card__loading-dot" />
              <span className="y-card__loading-dot" />
            </div>
          ) : (
            children
          )}
        </div>
      </div>
    )
  },
)

YCard.displayName = 'YCard'

export { YCard }
