// packages/svelte/src/select/select.svelte
<script lang="ts">
  import { createEventDispatcher, onMount, onDestroy } from 'svelte'

  interface Props<T = any> {
    options: T[]
    value?: T
    placeholder?: string
    disabled?: boolean
    size?: 'sm' | 'md' | 'lg'
    error?: boolean
    getLabel?: (option: T) => string
    getValue?: (option: T) => string
  }

  export let options: Props['options'] = []
  export let value: Props['value'] = undefined
  export let placeholder: Props['placeholder'] = 'Select...'
  export let disabled: Props['disabled'] = false
  export let size: Props['size'] = 'md'
  export let error: Props['error'] = false
  export let getLabel: Props['getLabel'] = undefined
  export let getValue: Props['getValue'] = undefined

  const dispatch = createEventDispatcher<{ change: any }>()

  let isOpen = false
  let highlightedIndex = -1
  let internalValue: any = undefined
  let triggerEl: HTMLButtonElement
  let containerEl: HTMLDivElement

  $: isControlled = value !== undefined
  $: currentValue = isControlled ? value : internalValue

  $: selectedLabel = currentValue != null ? getLabelFor(currentValue) : null

  $: classes = [
    'y-select',
    disabled ? 'y-select--disabled' : '',
    error ? 'y-select--error' : '',
  ].filter(Boolean).join(' ')

  function getLabelFor(opt: any): string {
    return getLabel ? getLabel(opt) : String(opt)
  }

  function handleSelect(opt: any) {
    if (!isControlled) internalValue = opt
    dispatch('change', opt)
    isOpen = false
    triggerEl?.focus()
  }

  function handleToggle() {
    if (disabled) return
    isOpen = !isOpen
  }

  function handleKeydown(e: KeyboardEvent) {
    if (disabled) return

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault()
        if (!isOpen) {
          isOpen = true
          highlightedIndex = 0
        } else {
          highlightedIndex = highlightedIndex < options.length - 1 ? highlightedIndex + 1 : 0
        }
        break
      case 'ArrowUp':
        e.preventDefault()
        if (!isOpen) {
          isOpen = true
          highlightedIndex = options.length - 1
        } else {
          highlightedIndex = highlightedIndex > 0 ? highlightedIndex - 1 : options.length - 1
        }
        break
      case 'Enter':
        e.preventDefault()
        if (isOpen && highlightedIndex >= 0) {
          handleSelect(options[highlightedIndex])
        } else {
          isOpen = true
        }
        break
      case 'Escape':
        e.preventDefault()
        isOpen = false
        break
      case 'Home':
        if (isOpen) { e.preventDefault(); highlightedIndex = 0 }
        break
      case 'End':
        if (isOpen) { e.preventDefault(); highlightedIndex = options.length - 1 }
        break
    }
  }

  function handleClickOutside(e: MouseEvent) {
    if (!containerEl?.contains(e.target as Node)) {
      isOpen = false
    }
  }

  $: if (!isOpen) highlightedIndex = -1

  onMount(() => document.addEventListener('mousedown', handleClickOutside))
  onDestroy(() => document.removeEventListener('mousedown', handleClickOutside))
</script>

<svelte:window on:keydown={handleKeydown} />

<div bind:this={containerEl} class={classes}>
  <button
    bind:this={triggerEl}
    type="button"
    class="y-select__trigger y-input y-input--{size}"
    {disabled}
    aria-haspopup="listbox"
    aria-expanded={isOpen}
    on:click={handleToggle}
  >
    <span class="y-select__value">
      {#if selectedLabel != null}
        <span>{selectedLabel}</span>
      {:else}
        <span class="y-select__placeholder">{placeholder}</span>
      {/if}
    </span>
    <span class="y-select__arrow" aria-hidden="true">▾</span>
  </button>
  {#if isOpen}
    <div class="y-select__dropdown" role="listbox">
      {#each options as option, index}
        <div
          role="option"
          aria-selected={currentValue === option}
          class="y-select__option {highlightedIndex === index ? 'y-select__option--active' : ''}"
          on:click={() => handleSelect(option)}
          on:mouseenter={() => (highlightedIndex = index)}
        >
          {getLabelFor(option)}
        </div>
      {/each}
    </div>
  {/if}
</div>

// packages/vue/src/select/select.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue'

export interface SelectProps<T = any> {
  options: T[]
  modelValue?: T
  defaultValue?: T
  placeholder?: string
  disabled?: boolean
  size?: 'sm' | 'md' | 'lg'
  error?: boolean
  getLabel?: (option: T) => string
  getValue?: (option: T) => string
}

const props = withDefaults(defineProps<SelectProps>(), {
  placeholder: 'Select...',
  disabled: false,
  size: 'md',
  error: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: any]
  'change': [value: any]
}>()

const isOpen = ref(false)
const highlightedIndex = ref(-1)
const internalValue = ref(props.defaultValue)
const triggerRef = ref<HTMLButtonElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)

const isControlled = computed(() => props.modelValue !== undefined)
const currentValue = computed(() => isControlled.value ? props.modelValue : internalValue.value)

function getLabelFor(opt: any): string {
  return props.getLabel ? props.getLabel(opt) : String(opt)
}

function handleSelect(opt: any) {
  if (!isControlled.value) internalValue.value = opt
  emit('update:modelValue', opt)
  emit('change', opt)
  isOpen.value = false
  triggerRef.value?.focus()
}

function handleToggle() {
  if (props.disabled) return
  isOpen.value = !isOpen.value
}

function handleKeydown(e: KeyboardEvent) {
  if (props.disabled) return

  switch (e.key) {
    case 'ArrowDown':
      e.preventDefault()
      if (!isOpen.value) {
        isOpen.value = true
        highlightedIndex.value = 0
      } else {
        highlightedIndex.value = highlightedIndex.value < props.options.length - 1
          ? highlightedIndex.value + 1 : 0
      }
      break
    case 'ArrowUp':
      e.preventDefault()
      if (!isOpen.value) {
        isOpen.value = true
        highlightedIndex.value = props.options.length - 1
      } else {
        highlightedIndex.value = highlightedIndex.value > 0
          ? highlightedIndex.value - 1 : props.options.length - 1
      }
      break
    case 'Enter':
      e.preventDefault()
      if (isOpen.value && highlightedIndex.value >= 0) {
        handleSelect(props.options[highlightedIndex.value])
      } else {
        isOpen.value = true
      }
      break
    case 'Escape':
      e.preventDefault()
      isOpen.value = false
      break
    case 'Home':
      if (isOpen.value) { e.preventDefault(); highlightedIndex.value = 0 }
      break
    case 'End':
      if (isOpen.value) { e.preventDefault(); highlightedIndex.value = props.options.length - 1 }
      break
  }
}

function handleClickOutside(e: MouseEvent) {
  if (!containerRef.value?.contains(e.target as Node)) {
    isOpen.value = false
  }
}

onMounted(() => document.addEventListener('mousedown', handleClickOutside))
onBeforeUnmount(() => document.removeEventListener('mousedown', handleClickOutside))

watch(isOpen, (val) => { if (!val) highlightedIndex.value = -1 })

const selectedLabel = computed(() =>
  currentValue.value != null ? getLabelFor(currentValue.value) : null,
)

const classes = computed(() =>
  [
    'y-select',
    props.disabled ? 'y-select--disabled' : '',
    props.error ? 'y-select--error' : '',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div ref="containerRef" :class="classes" @keydown="handleKeydown">
    <button
      ref="triggerRef"
      type="button"
      :class="`y-select__trigger y-input y-input--${size}`"
      :disabled="disabled"
      aria-haspopup="listbox"
      :aria-expanded="isOpen"
      @click="handleToggle"
    >
      <span class="y-select__value">
        <span v-if="selectedLabel != null">{{ selectedLabel }}</span>
        <span v-else class="y-select__placeholder">{{ placeholder }}</span>
      </span>
      <span class="y-select__arrow" aria-hidden="true">▾</span>
    </button>
    <div v-if="isOpen" class="y-select__dropdown" role="listbox">
      <div
        v-for="(option, index) in options"
        :key="getValue ? getValue(option) : index"
        role="option"
        :aria-selected="currentValue === option"
        :class="[
          'y-select__option',
          highlightedIndex === index ? 'y-select__option--active' : '',
        ]"
        @click="handleSelect(option)"
        @mouseenter="highlightedIndex = index"
      >
        {{ getLabelFor(option) }}
      </div>
    </div>
  </div>
</template>
