// packages/svelte/src/button/button.svelte
<script lang="ts">
  interface Props {
    variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'
    size?: 'sm' | 'md' | 'lg'
    disabled?: boolean
    loading?: boolean
    loadingText?: string
    block?: boolean
    htmlType?: 'button' | 'submit' | 'reset'
    icon?: string
    onclick?: (e: MouseEvent) => void
  }

  export let variant: Props['variant'] = 'primary'
  export let size: Props['size'] = 'md'
  export let disabled: Props['disabled'] = false
  export let loading: Props['loading'] = false
  export let loadingText: Props['loadingText'] = 'Loading'
  export let block: Props['block'] = false
  export let htmlType: Props['htmlType'] = 'button'
  export let onclick: Props['onclick'] = undefined

  $: isDisabled = disabled || loading
  $: classes = ['y-btn', `y-btn--${variant}`, `y-btn--${size}`, block ? 'y-btn--block' : '']
    .filter(Boolean)
    .join(' ')
</script>

<button
  type={htmlType}
  disabled={isDisabled}
  aria-disabled={isDisabled || undefined}
  aria-busy={loading || undefined}
  class={classes}
  on:click={onclick}
>
  {#if loading}
    <span aria-hidden="true" class="y-btn__spinner" />
    <span class="sr-only">{loadingText}</span>
  {/if}
  <span class="y-btn__label">
    <slot />
  </span>
</button>

// packages/vue/src/button/button.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'
  size?: 'sm' | 'md' | 'lg'
  disabled?: boolean
  loading?: boolean
  loadingText?: string
  block?: boolean
  htmlType?: 'button' | 'submit' | 'reset'
  icon?: string
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
  loading: false,
  loadingText: 'Loading',
  block: false,
  htmlType: 'button',
})

const isDisabled = computed(() => props.disabled || props.loading)

const classes = computed(() =>
  [
    'y-btn',
    `y-btn--${props.variant}`,
    `y-btn--${props.size}`,
    props.block ? 'y-btn--block' : '',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <button
    :type="htmlType"
    :disabled="isDisabled"
    :aria-disabled="isDisabled || undefined"
    :aria-busy="loading || undefined"
    :class="classes"
  >
    <template v-if="loading">
      <span aria-hidden="true" class="y-btn__spinner" />
      <span class="sr-only">{{ loadingText }}</span>
    </template>
    <span class="y-btn__label">
      <slot />
    </span>
  </button>
</template>
