// packages/react/src/dialog/dialog.tsx
import React, { forwardRef, useEffect, useRef, useCallback } from 'react'
import { YIcon } from '../icon'

export interface DialogProps {
  open?: boolean
  title?: string
  closable?: boolean
  mask?: boolean
  maskClosable?: boolean
  width?: string | number
  footer?: React.ReactNode
  children?: React.ReactNode
  className?: string
  onClose?: () => void
}

const YDialog = forwardRef<HTMLDivElement, DialogProps>(
  (
    {
      open = false,
      title,
      closable = true,
      mask = true,
      maskClosable = true,
      width,
      footer,
      children,
      className,
      onClose,
    },
    ref,
  ) => {
    const dialogRef = useRef<HTMLDivElement>(null)
    const previousFocus = useRef<HTMLElement | null>(null)

    const handleOverlayClick = useCallback(() => {
      if (maskClosable && mask) onClose?.()
    }, [maskClosable, mask, onClose])

    const handleDialogClick = useCallback((e: React.MouseEvent) => {
      e.stopPropagation()
    }, [])

    const handleKeyDown = useCallback(
      (e: KeyboardEvent) => {
        if (e.key === 'Escape' && closable) onClose?.()
      },
      [closable, onClose],
    )

    useEffect(() => {
      if (open) {
        previousFocus.current = document.activeElement as HTMLElement
        document.addEventListener('keydown', handleKeyDown)
        document.body.style.overflow = 'hidden'
      }
      return () => {
        document.removeEventListener('keydown', handleKeyDown)
        document.body.style.overflow = ''
        if (previousFocus.current) {
          previousFocus.current.focus()
        }
      }
    }, [open, handleKeyDown])

    if (!open) return null

    const dialogStyle: React.CSSProperties = width != null
      ? { width: typeof width === 'number' ? `${width}px` : width }
      : {}

    const classes = ['y-dialog', className || ''].filter(Boolean).join(' ')

    return (
      <div className="y-dialog-overlay" onClick={handleOverlayClick}>
        {mask && <div className="y-dialog-mask" />}
        <div
          ref={(node) => {
            (dialogRef as React.MutableRefObject<HTMLDivElement | null>).current = node
            if (typeof ref === 'function') ref(node)
            else if (ref) (ref as React.MutableRefObject<HTMLDivElement | null>).current = node
          }}
          className={classes}
          role="dialog"
          aria-modal="true"
          aria-labelledby={title ? 'y-dialog-title' : undefined}
          style={dialogStyle}
          onClick={handleDialogClick}
        >
          {(title || closable) && (
            <div className="y-dialog__header">
              {title && (
                <h2 id="y-dialog-title" className="y-dialog__title">
                  {title}
                </h2>
              )}
              {closable && (
                <button
                  type="button"
                  className="y-dialog__close"
                  aria-label="Close"
                  onClick={onClose}
                >
                  <YIcon name="x" size={16} />
                </button>
              )}
            </div>
          )}
          <div className="y-dialog__body">{children}</div>
          {footer && <div className="y-dialog__footer">{footer}</div>}
        </div>
      </div>
    )
  },
)

YDialog.displayName = 'YDialog'

export { YDialog }

// packages/svelte/src/dialog/dialog.svelte
<script lang="ts">
  import { createEventDispatcher, onMount, onDestroy } from 'svelte'
  import { YIcon } from '../icon'

  interface Props {
    open?: boolean
    title?: string
    closable?: boolean
    mask?: boolean
    maskClosable?: boolean
    width?: string | number
  }

  export let open: Props['open'] = false
  export let title: Props['title'] = undefined
  export let closable: Props['closable'] = true
  export let mask: Props['mask'] = true
  export let maskClosable: Props['maskClosable'] = true
  export let width: Props['width'] = undefined

  const dispatch = createEventDispatcher<{ close: void }>()

  let previousFocus: HTMLElement | null = null

  function handleClose() {
    dispatch('close')
  }

  function handleOverlayClick() {
    if (maskClosable && mask) handleClose()
  }

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape' && closable) handleClose()
  }

  $: if (open) {
    previousFocus = document.activeElement as HTMLElement
    document.addEventListener('keydown', handleKeydown)
    document.body.style.overflow = 'hidden'
  } else {
    document.removeEventListener('keydown', handleKeydown)
    document.body.style.overflow = ''
    if (previousFocus) previousFocus.focus()
  }

  onDestroy(() => {
    document.removeEventListener('keydown', handleKeydown)
    document.body.style.overflow = ''
  })

  $: dialogStyle = width != null
    ? `width: ${typeof width === 'number' ? `${width}px` : width}`
    : ''
</script>

{#if open}
  <div class="y-dialog-overlay" on:click={handleOverlayClick} role="presentation">
    {#if mask}
      <div class="y-dialog-mask" />
    {/if}
    <div
      class="y-dialog"
      role="dialog"
      aria-modal="true"
      aria-labelledby={title ? 'y-dialog-title' : undefined}
      style={dialogStyle}
      on:click|stopPropagation
      on:keydown|stopPropagation
    >
      {#if title || closable}
        <div class="y-dialog__header">
          {#if title}
            <h2 id="y-dialog-title" class="y-dialog__title">{title}</h2>
          {/if}
          {#if closable}
            <button
              type="button"
              class="y-dialog__close"
              aria-label="Close"
              on:click={handleClose}
            >
              <YIcon name="x" size={16} />
            </button>
          {/if}
        </div>
      {/if}
      <div class="y-dialog__body">
        <slot />
      </div>
      {#if $$slots.footer}
        <div class="y-dialog__footer">
          <slot name="footer" />
        </div>
      {/if}
    </div>
  </div>
{/if}
