// packages/svelte/src/form-field/YFormField.svelte
<script lang="ts">
  interface Props {
    label?: string
    name: string
    error?: string
    required?: boolean
    hint?: string
    disabled?: boolean
  }

  export let name: Props['name']
  export let label: Props['label'] = undefined
  export let error: Props['error'] = undefined
  export let required: Props['required'] = false
  export let hint: Props['hint'] = undefined
  export let disabled: Props['disabled'] = false

  $: fieldId = `y-field-${name}`
  $: errorId = `${fieldId}-error`
  $: classes = [
    'y-form-field',
    disabled ? 'y-form-field--disabled' : '',
  ].filter(Boolean).join(' ')
</script>

<div class={classes}>
  {#if label}
    <label for={fieldId} class="y-form-field__label">
      {label}
      {#if required}<span class="y-form-field__required">*</span>{/if}
    </label>
  {/if}
  <slot />
  {#if hint && !error}
    <span class="y-form-field__hint">{hint}</span>
  {/if}
  {#if error}
    <span id={errorId} class="y-form-field__error" role="alert">{error}</span>
  {/if}
</div>

// packages/vue/src/form-field/YFormField.vue
<script setup lang="ts">
import { computed } from 'vue'

export interface FormFieldProps {
  label?: string
  name: string
  error?: string
  required?: boolean
  hint?: string
  disabled?: boolean
}

const props = withDefaults(defineProps<FormFieldProps>(), {
  required: false,
  disabled: false,
})

const fieldId = computed(() => `y-field-${props.name}`)
const errorId = computed(() => `${fieldId.value}-error`)

const classes = computed(() =>
  [
    'y-form-field',
    props.disabled ? 'y-form-field--disabled' : '',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div :class="classes">
    <label v-if="label" :for="fieldId" class="y-form-field__label">
      {{ label }}
      <span v-if="required" class="y-form-field__required">*</span>
    </label>
    <slot />
    <span v-if="hint && !error" class="y-form-field__hint">{{ hint }}</span>
    <span v-if="error" :id="errorId" class="y-form-field__error" role="alert">
      {{ error }}
    </span>
  </div>
</template>
