// packages/react/src/input/input.tsx
import React, { forwardRef, useState, useCallback } from 'react'
import { YIcon } from '../icon'

export interface InputProps {
  type?: 'text' | 'password' | 'email' | 'number' | 'tel' | 'url' | 'search'
  value?: string
  defaultValue?: string
  placeholder?: string
  disabled?: boolean
  readOnly?: boolean
  size?: 'sm' | 'md' | 'lg'
  error?: boolean
  prefix?: React.ReactNode
  suffix?: React.ReactNode
  clearable?: boolean
  name?: string
  maxLength?: number
  autoComplete?: string
  className?: string
  onChange?: (value: string) => void
  onFocus?: (e: React.FocusEvent<HTMLInputElement>) => void
  onBlur?: (e: React.FocusEvent<HTMLInputElement>) => void
}

const YInput = forwardRef<HTMLInputElement, InputProps>(
  (
    {
      type = 'text',
      value,
      defaultValue,
      placeholder,
      disabled = false,
      readOnly = false,
      size = 'md',
      error = false,
      prefix,
      suffix,
      clearable = false,
      name,
      maxLength,
      autoComplete,
      className,
      onChange,
      onFocus,
      onBlur,
    },
    ref,
  ) => {
    const [internalValue, setInternalValue] = useState(defaultValue ?? '')
    const isControlled = value !== undefined
    const currentValue = isControlled ? value : internalValue

    const handleChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => {
        const newValue = e.target.value
        if (!isControlled) setInternalValue(newValue)
        onChange?.(newValue)
      },
      [isControlled, onChange],
    )

    const handleClear = useCallback(() => {
      if (!isControlled) setInternalValue('')
      onChange?.('')
    }, [isControlled, onChange])

    const wrapperClasses = [
      'y-input-wrapper',
      error ? 'y-input-wrapper--error' : '',
      disabled ? 'y-input-wrapper--disabled' : '',
      className || '',
    ]
      .filter(Boolean)
      .join(' ')

    return (
      <div className={wrapperClasses}>
        {prefix && <span className="y-input__prefix">{prefix}</span>}
        <input
          ref={ref}
          type={type}
          value={currentValue}
          placeholder={placeholder}
          disabled={disabled}
          readOnly={readOnly}
          name={name}
          maxLength={maxLength}
          autoComplete={autoComplete}
          className={`y-input y-input--${size}`}
          aria-invalid={error || undefined}
          onChange={handleChange}
          onFocus={onFocus}
          onBlur={onBlur}
        />
        {clearable && currentValue && !disabled && !readOnly && (
          <button
            type="button"
            className="y-input__suffix cursor-pointer"
            onClick={handleClear}
            aria-label="Clear"
          >
            <YIcon name="x" size={14} />
          </button>
        )}
        {suffix && <span className="y-input__suffix">{suffix}</span>}
      </div>
    )
  },
)

YInput.displayName = 'YInput'

export { YInput }

// packages/vue/src/input/input.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { YIcon } from '../icon'

export interface InputProps {
  type?: 'text' | 'password' | 'email' | 'number' | 'tel' | 'url' | 'search'
  modelValue?: string
  defaultValue?: string
  placeholder?: string
  disabled?: boolean
  readonly?: boolean
  size?: 'sm' | 'md' | 'lg'
  error?: boolean
  clearable?: boolean
  name?: string
  maxLength?: number
  autoComplete?: string
}

const props = withDefaults(defineProps<InputProps>(), {
  type: 'text',
  disabled: false,
  readonly: false,
  size: 'md',
  error: false,
  clearable: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'change': [value: string]
  'focus': [e: FocusEvent]
  'blur': [e: FocusEvent]
}>()

const internalValue = ref(props.defaultValue ?? '')
const isControlled = computed(() => props.modelValue !== undefined)
const currentValue = computed(() => isControlled.value ? props.modelValue! : internalValue.value)

function handleChange(e: Event) {
  const newValue = (e.target as HTMLInputElement).value
  if (!isControlled.value) internalValue.value = newValue
  emit('update:modelValue', newValue)
  emit('change', newValue)
}

function handleClear() {
  if (!isControlled.value) internalValue.value = ''
  emit('update:modelValue', '')
  emit('change', '')
}

const wrapperClasses = computed(() =>
  [
    'y-input-wrapper',
    props.error ? 'y-input-wrapper--error' : '',
    props.disabled ? 'y-input-wrapper--disabled' : '',
  ]
    .filter(Boolean)
    .join(' '),
)
</script>

<template>
  <div :class="wrapperClasses">
    <span v-if="$slots.prefix" class="y-input__prefix">
      <slot name="prefix" />
    </span>
    <input
      :type="type"
      :value="currentValue"
      :placeholder="placeholder"
      :disabled="disabled"
      :readonly="readonly"
      :name="name"
      :maxlength="maxLength"
      :autocomplete="autoComplete"
      :class="`y-input y-input--${size}`"
      :aria-invalid="error || undefined"
      @input="handleChange"
      @focus="emit('focus', $event)"
      @blur="emit('blur', $event)"
    />
    <button
      v-if="clearable && currentValue && !disabled && !readonly"
      type="button"
      class="y-input__suffix cursor-pointer"
      aria-label="Clear"
      @click="handleClear"
    >
      <YIcon name="x" :size="14" />
    </button>
    <span v-if="$slots.suffix" class="y-input__suffix">
      <slot name="suffix" />
    </span>
  </div>
</template>
